In [5]:
import numpy as np
import random

# Initialiser la grille du sudoku à 9x9
grille = np.zeros((9,9))

def possible(y,x,n):
    # Vérifier si le nombre n peut être placé à la position (y,x)
    global grille
    for i in range(0,9):
        if grille[y][i] == n:
            return False
    for i in range(0,9):
        if grille[i][x] == n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grille[y0+i][x0+j] == n:
                return False
    return True

def remplir_grille():
    # Remplir la grille du sudoku de façon aléatoire
    global grille
    for y in range(9):
        for x in range(9):
            if grille[y][x] == 0:  # Si la case est vide
                for n in range(1,10):  # Pour chaque nombre de 1 à 9
                    if possible(y,x,n):  # Si le nombre peut être placé
                        grille[y][x] = n  # Place le nombre
                        remplir_grille()  # Continue à remplir la grille
                        if np.count_nonzero(grille) == 81:
                            return
                        grille[y][x] = 0  # Si le nombre ne peut pas être placé, remets la case à 0
                return
    print(grille)

remplir_grille()

def enlever_cases():
    # Enlever des nombres de la grille de manière aléatoire
    global grille
    for i in range(60):  # Nous allons enlever 60 cases
        while True:
            x, y = random.randint(0,8), random.randint(0,8)
            if grille[y][x] != 0:
                grille[y][x] = 0
                break

enlever_cases()
print(grille)


[[1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [4. 5. 6. 7. 8. 9. 1. 2. 3.]
 [7. 8. 9. 1. 2. 3. 4. 5. 6.]
 [2. 1. 4. 3. 6. 5. 8. 9. 7.]
 [3. 6. 5. 8. 9. 7. 2. 1. 4.]
 [8. 9. 7. 2. 1. 4. 3. 6. 5.]
 [5. 3. 1. 6. 4. 2. 9. 7. 8.]
 [6. 4. 2. 9. 7. 8. 5. 3. 1.]
 [9. 7. 8. 5. 3. 1. 6. 4. 2.]]
[[1. 0. 0. 4. 5. 0. 0. 8. 0.]
 [0. 0. 0. 7. 8. 0. 0. 0. 0.]
 [7. 8. 9. 0. 0. 0. 0. 0. 0.]
 [2. 0. 4. 3. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 2. 0. 7. 0.]
 [0. 0. 2. 0. 0. 8. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 2.]]
